"""Initial schema: brands, products, product_variants, crawl_runs,
crawl_run_brands, plus devices/chat_messages/session_events/
query_intent_cache/collections/users/wishlist_items.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-16 12:04:03.720969

"""
import json
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('crawl_enabled', sa.Boolean(), nullable=False),
    sa.Column('department', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('filter_definition', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('query_intent_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_hash', sa.String(length=100), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=False),
    sa.Column('extracted_intent', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_hash')
    )
    op.create_index(op.f('ix_query_intent_cache_expires_at'), 'query_intent_cache', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('preferred_size', sa.String(length=10), nullable=True),
    sa.Column('department', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('crawl_run_brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('crawl_run_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('products_fetched', sa.Integer(), nullable=False),
    sa.Column('products_mapped', sa.Integer(), nullable=False),
    sa.Column('products_upserted', sa.Integer(), nullable=False),
    sa.Column('products_unchanged', sa.Integer(), nullable=False),
    sa.Column('products_removed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_run_brands_brand_id'), 'crawl_run_brands', ['brand_id'], unique=False)
    op.create_index(op.f('ix_crawl_run_brands_crawl_run_id'), 'crawl_run_brands', ['crawl_run_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('composite_key', sa.String(length=200), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('product_family', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('shopify_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('department', sa.String(length=20), nullable=True),
    sa.Column('is_kids', sa.Boolean(), nullable=False),
    sa.Column('age_ranges_months', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occasion', sa.String(length=100), nullable=True),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sizes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('color_images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('primary_image_url', sa.String(length=1000), nullable=True),
    sa.Column('secondary_image_url', sa.String(length=1000), nullable=True),
    sa.Column('product_url', sa.String(length=1000), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_model_version', sa.String(length=50), nullable=True),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('missing_streak', sa.Integer(), nullable=False),
    sa.Column('raw_shopify_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'external_id', name='uq_products_brand_external')
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_composite_key'), 'products', ['composite_key'], unique=True)
    op.create_index(op.f('ix_products_department'), 'products', ['department'], unique=False)
    op.create_index(op.f('ix_products_embedded_at'), 'products', ['embedded_at'], unique=False)
    op.create_index(op.f('ix_products_in_stock'), 'products', ['in_stock'], unique=False)
    op.create_index(op.f('ix_products_is_kids'), 'products', ['is_kids'], unique=False)
    op.create_index(op.f('ix_products_occasion'), 'products', ['occasion'], unique=False)
    op.create_index(op.f('ix_products_product_family'), 'products', ['product_family'], unique=False)
    op.create_table('session_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_events_created_at'), 'session_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_session_events_session_id'), 'session_events', ['session_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('external_variant_id', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('extra_options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'external_variant_id', name='uq_variants_product_external')
    )
    op.create_index(op.f('ix_product_variants_available'), 'product_variants', ['available'], unique=False)
    op.create_index(op.f('ix_product_variants_color'), 'product_variants', ['color'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_size'), 'product_variants', ['size'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'product_id')
    )
    op.create_index(op.f('ix_wishlist_items_user_id'), 'wishlist_items', ['user_id'], unique=False)
    # ### end Alembic commands ###

    _seed_brands()


def _seed_brands() -> None:
    """Seed the 25 tracked brand sites (seed/brands.json)."""
    seed_file = Path(__file__).parent.parent.parent / "seed" / "brands.json"
    with open(seed_file) as f:
        brands = json.load(f)

    bind = op.get_bind()
    for brand in brands:
        bind.execute(
            text(
                """
                INSERT INTO brands (id, name, slug, domain, department, is_active, crawl_enabled, created_at)
                VALUES (gen_random_uuid(), :name, :slug, :domain, :department, true, true, now())
                """
            ),
            {
                "name": brand["name"],
                "slug": brand["slug"],
                "domain": brand["domain"],
                "department": brand["department"],
            },
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlist_items_user_id'), table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index(op.f('ix_product_variants_size'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_color'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_available'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_session_events_session_id'), table_name='session_events')
    op.drop_index(op.f('ix_session_events_created_at'), table_name='session_events')
    op.drop_table('session_events')
    op.drop_index(op.f('ix_products_product_family'), table_name='products')
    op.drop_index(op.f('ix_products_occasion'), table_name='products')
    op.drop_index(op.f('ix_products_is_kids'), table_name='products')
    op.drop_index(op.f('ix_products_in_stock'), table_name='products')
    op.drop_index(op.f('ix_products_embedded_at'), table_name='products')
    op.drop_index(op.f('ix_products_department'), table_name='products')
    op.drop_index(op.f('ix_products_composite_key'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_crawl_run_brands_crawl_run_id'), table_name='crawl_run_brands')
    op.drop_index(op.f('ix_crawl_run_brands_brand_id'), table_name='crawl_run_brands')
    op.drop_table('crawl_run_brands')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_query_intent_cache_expires_at'), table_name='query_intent_cache')
    op.drop_table('query_intent_cache')
    op.drop_table('devices')
    op.drop_table('crawl_runs')
    op.drop_table('collections')
    op.drop_table('brands')
    # ### end Alembic commands ###
